# Generated by Django 4.1.1 on 2022-10-18 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=50)),
                ('creationDate', models.DateTimeField(default=datetime.datetime(2022, 10, 18, 22, 26, 46, 599935))),
                ('releaseDate', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
