# Generated by Django 4.1.1 on 2022-10-19 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='creationDate',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
