# Generated by Django 4.1.1 on 2022-10-19 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_is_approved_alter_album_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creationDate',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
