# Generated by Django 4.1.1 on 2022-10-20 16:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=model_utils.fields.StatusField(choices=[('creationDate', 'creationDate')], default='creationDate', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='album',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
