# Generated by Django 4.1.1 on 2022-10-20 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_creationdate_album_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='status',
        ),
        migrations.RemoveField(
            model_name='album',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
