# Generated by Django 4.1.1 on 2022-10-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_image',
        ),
    ]
