# Generated by Django 4.1.2 on 2022-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_remove_song_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.ImageField(default=None, upload_to='songs/photos'),
        ),
    ]
