# Generated by Django 4.1.1 on 2022-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='socialLink',
            field=models.URLField(max_length=100),
        ),
    ]
